### ISSUE TITLE
ClasspathSuite runner fails on Android

### ISSUE THREAD

**Issue by mbolotov** [takari/takari-cpsuite#17]
I've encountered a problem when running a test by ClasspathSuite runner on Android platform:

```
import org.junit.extensions.cpsuite.ClasspathSuite;
import org.junit.runner.RunWith;

@RunWith(ClasspathSuite.class)
public class AllTabletTests {
}

```
The problem seems to be caused by Android specific value for "java.class.path" property: it's always '.'
See https://developer.android.com/reference/java/lang/System.html

So it fails with the following exception:

> java.lang.NullPointerException: Attempt to get length of null array
> at org.junit.extensions.cpsuite.RecursiveFilenameIterator.getInnerIterators(RecursiveFilenameIterator.java:46)
> at org.junit.extensions.cpsuite.RecursiveFilenameIterator.<init>(RecursiveFilenameIterator.java:36)
> at org.junit.extensions.cpsuite.RecursiveFilenameIterator.<init>(RecursiveFilenameIterator.java:29)
> at org.junit.extensions.cpsuite.ClasspathClassesFinder.gatherClassesInRoot(ClasspathClassesFinder.java:65)
> at org.junit.extensions.cpsuite.ClasspathClassesFinder.findClassesInRoots(ClasspathClassesFinder.java:50)
> at org.junit.extensions.cpsuite.ClasspathClassesFinder.findClassesInClasspath(ClasspathClassesFinder.java:44)
> at org.junit.extensions.cpsuite.ClasspathClassesFinder.find(ClasspathClassesFinder.java:33)
> at org.junit.extensions.cpsuite.ClasspathSuite.getSortedTestclasses(ClasspathSuite.java:127)
> at org.junit.extensions.cpsuite.ClasspathSuite.<init>(ClasspathSuite.java:117)
> at org.junit.extensions.cpsuite.ClasspathSuite.<init>(ClasspathSuite.java:110)
> at java.lang.reflect.Constructor.newInstance0(Native Method)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
> at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:107)
> at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
> at android.support.test.internal.runner.junit4.AndroidAnnotatedBuilder.runnerForClass(AndroidAnnotatedBuilder.java:77)
> at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
> at org.junit.runner.Computer.getRunner(Computer.java:40)
> at org.junit.runner.Computer$1.runnerForClass(Computer.java:31)
> at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
> at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
> at org.junit.runners.Suite.<init>(Suite.java:81)
> at org.junit.runner.Computer.getSuite(Computer.java:28)
> at android.support.test.internal.runner.TestRequestBuilder.classes(TestRequestBuilder.java:789)
> at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:753)
> at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
> at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
> at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
>

**Comment by timtheguy** [comment]
I've also experienced this when casually trying to use this package in Android - did you ever find a solution?

**Comment by mbolotov** [comment]
As far as I remember - we've ending up with an external runner that select and run the test set.

**Comment by timtheguy** [comment]
Thank you for the response - if you happen to recall the name of the runner, do let me know! Cheers

**Comment by mbolotov** [comment]
It's our locally developed runner, we didn't open source it. By 'external' I mean external to the junit system.
